### ISSUE TITLE
Core.Game.Game.stats broken

### ISSUE THREAD

**Issue by hasoart** [hasoart/pymania#1]
Все размеры в методе Core/Game.Game.stats в пикселях, что сломается при изменении размеров экрана. Фонт импортируется неправильно, надо пофиксить. Добавлены картинки для ранков и (300, 100, 50, miss), так что надо переписать код под это. Стоит так же перенести функцию в Utils.ui_objects так как она больше графическая и довольно массивная в плане кода.

**Comment by SVektor8** [comment]
Corrected
