### ISSUE TITLE
Core.Game.ScoreMaster.get_hit_counts works with a bug

### ISSUE THREAD

**Issue by SVektor8** [hasoart/pymania#2]
При завершении игры в конце карты я получил ошибку
"C:\Users\Viktor\Documents\PyLabs2021\pymania\Core\Game.py", line 137, in get_rank
have_misses = bool(self.get_hit_counts()[3])
File "C:\Users\Viktor\Documents\PyLabs2021\pymania\Core\Game.py", line 121, in get_hit_counts
raise ValueError("Invalid value in score list")
ValueError: Invalid value in score list
Видимо, из-за того, что в конце карты слайдер был отпущен раньше времени (карта Uwa So Holiday, сложность easy) @hasoart

**Comment by hasoart** [comment]
Пофиксил.
